name: RestAssured Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      timeout-minutes: 30
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test
      run: |
        mvn clean test
        mvn allure:report

#     - name: Upload Allure Report
#       uses: actions/upload-artifact@v3
#       with:
#         name: allure-report
#         path: ./target/allure-results/

#     - name: GitHub Pages action
#       uses: peaceiris/actions-gh-pages@v3.9.3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./target/allure-results/
#         publish_branch: gh-pages

    - uses: vimtor/action-zip@v1
      timeout-minutes: 30
      if: always()
      with:
        files: ./target/allure-results/
        dest: ./allure-results.zip

    - uses: actions/upload-artifact@v3
      timeout-minutes: 30
      if: always()
      with:
        name: allure-results
        path: ./allure-results.zip
