name: Measure code coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        timeout-minutes: 30
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        if: always()
        run: |
          mvn clean test
          mvn jacoco:report
        continue-on-error: true    

      # - name: Upload Report
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: report.xml
      #     path: ${{ github.workspace }}/target/site/jacoco/index.html
      
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/target/site/jacoco/index.html
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: '# :lobster: Coverage Report'
          update-comment: true
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'
